version: "3.7"

networks:
  first-app.com:

services:
  orderer.first-app.com:
    container_name: orderer.first-app.com
    image: hyperledger/fabric-orderer
    environment:
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    # enabled TLS
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
    - ./.volumes/channel-config/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./.volumes/crypto-config/ordererOrganizations/first-app.com/orderers/orderer.first-app.com:/var/hyperledger/orderer
    networks:
    - first-app.com

  peer0.org1.first-app.com:
    container_name: peer0.org1.first-app.com
    image: hyperledger/fabric-peer
    environment:
    - CORE_PEER_ID=peer0.org1.first-app.com
    - CORE_PEER_ADDRESS=peer0.org1.first-app.com:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.first-app.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.first.com:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    # enabled TLS
    - CORE_PEER_TLS_ENABLED=true
    volumes:
    - ./.volumes/crypto-config/peerOrganizations/org1.first-app.com/peers/peer0.org1.first-app.com/msp:/etc/hyperledger/fabric/msp
    - ./.volumes/crypto-config/peerOrganizations/org1.first-app.com/peers/peer0.org1.first-app.com/tls:/etc/hyperledger/fabric/tls
    networks:
    - first-app.com
