OrdererOrgs:
- Name: Orderer
  Domain: first-app.com
  Specs:
  - Hostname: orderer

PeerOrgs:
- Name: Org1
  Domain: org1.first-app.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org2
  Domain: org2.first-app.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org3
  Domain: org3.first-app.com
  Template:
    Count: 1
  Users:
    Count: 1
